schemaVersion: "1.2"
endpoints:
    - name: miner-node-05
      displayName: WSO2 Blockchain Miner node 05
      service:
        basePath: /
        port: 8545
      type: REST
      networkVisibilities:
        - Public
    - name: udp-miner-node-05
      displayName: WSO2 Blockchain sealer node 05 P2P UDP service
      service:
        basePath: /
        port: 30303
      type: UDP
      networkVisibilities:
        - Project
    - name: tcp-miner-node-05
      displayName: WSO2 Blockchain sealer node 05 P2P TCP service
      service:
        basePath: /
        port: 30303
      type: TCP
      networkVisibilities:
        - Project
