schemaVersion: "1.2"
endpoints:
    - name: miner-node-01
      displayName: WSO2 Blockchain RPC node 01
      service:
        basePath: /
        port: 8545
      type: REST
      networkVisibilities:
        - Public
    - name: udp-miner-node-01
      displayName: WSO2 Blockchain node 01 P2P UDP service
      service:
        basePath: /
        port: 30303
      type: UDP
      networkVisibilities:
        - Project
    - name: tcp-miner-node-01
      displayName: WSO2 Blockchain node 01 P2P TCP service
      service:
        basePath: /
        port: 30303
      type: TCP
      networkVisibilities:
        - Project
