schemaVersion: "1.2"
endpoints:
    - name: miner-node-04
      displayName: WSO2 Blockchain RPC node 04
      service:
        basePath: /
        port: 8545
      type: REST
      networkVisibilities:
        - Public
    - name: udp-miner-node-04
      displayName: WSO2 Blockchain node 04 P2P service
      service:
        basePath: /
        port: 30303
      type: TCP
      networkVisibilities:
        - Project
